### ISSUE TITLE
Check versions with PHP

### ISSUE THREAD

**Issue by noplanman** [aalaesar/upgrade-nextcloud#2]
After having a look at the `nc_check_versions.sh` script, why not just use PHP?

With PHP, you could easily make a little script that includes the 2 `version.php` files and compares versions etc. using nice PHP functions instead of messing around with arrays and bash-isms.

Especially `version_compare` saves like a billion lines of code 😜 

I'd happily PR this if you like.

**Comment by aalaesar** [comment]
Well, you got me. What can I say.... 🤔 
> When you own a hammer, every problem looks like a nail.

I wanted a quick and "reliable" way of checking version
and... I 'm quick & with a lot xp on bash while I have very few xp on php reading only

If you have time, you're welcome to PR a new and shiny script to compare the versions. 😄 
Regards,
Aal.

**Comment by noplanman** [comment]
> When you own a hammer, every problem looks like a nail.

😄 

Will have a look at this...

**Comment by noplanman** [comment]
I'm busy on this one and see that you compare the timestamps to check if the versions are the same. Is there a special reason why you didn't just compare the version numbers?

Looking at the history of the `version.php` file, some of them don't even have the build information.

**Comment by aalaesar** [comment]
It's just a trick to simplify the version comparison.
With bash, I needed to compare version number "level by level" in 2 loops and test 3-4 cases at each iteration.
while it's easier to compare once 2 timestamps and remove 1-2 tests in the loops.

**Comment by noplanman** [comment]
Right, that makes perfect sense then.

In the PHP version I'll skip that part and use the version directly 😊

**Comment by aalaesar** [comment]
Continuing from pull request #4:
> Another thing that would be great, is to check versions before downloading the whole zip file.
What could be done, is to just fetch the version.php file from the GitHub repo and compare with that.
To download the whole zip every time to just say "version is the same" doesn't make sense.

I'm not sure how the version.php file can be downloaded from github for any specific version available in the nextcloud official download site.
Github tags and releases are available as archive zip or tar.gz and main stable branch will always have the latest version available for the file.
In fact ...
What can be done is adding a task checking if the nextcloud_version parameter is equal to the one installed. :smile:

**Comment by noplanman** [comment]
> I'm not sure how the version.php file can be downloaded from github for any specific version available in the nextcloud official download site.

Well, for the normal versions this works (replacing `[version]` with the version number):
`https://raw.githubusercontent.com/nextcloud/server/v[version]/version.php`

You talking about the daily ones by date?
The only reason I can think of why anybody would get a specific daily one (which aren't necessarily stable) is if there is a bug in some future one after it.
Otherwise I really don't know why somebody would choose a daily one. For those it could be an exception and the whole file would be downloaded.

> What can be done is adding a task checking if the nextcloud_version parameter is equal to the one installed. 😄

Haxter 😝 As a simple check, totally!
